### ISSUE TITLE
Editing Animation Speed with decimals brings up Invalid Value, when decimals are not invalid

### ISSUE THREAD

**Issue by Reshirou** [KyonkoYuuki/YaBACOrganizer#1]
You cannot edit an Animation Speed value to have decimals, like 1.1, 1.5, 1.74, 2.6, etc, despite all of those numbers being valid and recognized by Xenoverse if you manually XML edit

If you edit to a number with a decimal, move to another bac index, and then come back to the one you edited, it will have reverted back to it's original value (including if it's original value already used a decimal in the first place, like transition compression values)

using the replace function, as well, brings a straight up Invalid Value error at the bottom

**Comment by KyonkoYuuki** [comment]
![image](https://user-images.githubusercontent.com/51934173/65933695-98f6c780-e3e0-11e9-8329-6240f8ce2759.png)

I can edit the speed values fine.  Replace function is broken though for floats (same with other tools as well)

**Comment by KyonkoYuuki** [comment]
Found the bug and its fixed, here and other tools as well.
