### ISSUE TITLE
YaBAC v0.2.2 : odd behaviors on ThrowHandler 

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBACOrganizer#10]
YaBAC v0.2.2 sometimes reads "Bone User Connects to Victim From" as out-of-range values, such as 0x79 or 0x85. but the max bone flag is 0x18

also, YaBAC still doesn't read Victim_Displacement values properly.

![image](https://user-images.githubusercontent.com/47185022/82840558-b5012900-9edb-11ea-8eb1-be456e0f1dcc.png)

**Comment by KyonkoYuuki** [comment]
Will change the Connection stuff to be like how its done in the latest BCS organizer.

Will once again take a look at throws.  Which BAC is this btw, because I need to know if I messed up the TYPE17 calculation or not.

**Comment by KyonkoYuuki** [comment]
So the type17 offset calculation didn't take into account TYPE17BIG, so now it does and it loads fine now.
