### ISSUE TITLE
YaBAC v0.2.2 : HomeingMovements's Speed Parameter does not accept decimal values 

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBACOrganizer#11]
in HomeingMovement, "Speed" can be an integer value (frame)
or a decimal value (actual speed)
The logic of HM will change accordingly. but YaBAC doesn't accept decimal values in the text field.

and if a skill did have a decimal value, YaBAC will read the value (and save it) as 65535

**Comment by KyonkoYuuki** [comment]
example please of the float version.

Genser at least always viewed the speed modifier as an U32 value and not a FLOAT

**Comment by KyonkoYuuki** [comment]
Feel free to reopen, but LB's XML Serializer doesn't like it as a float either.
![image](https://user-images.githubusercontent.com/51934173/82851474-f5f24100-9ecd-11ea-95d2-490fab05c269.png)

genser will still compile it, but it will convert the float to an int first.
