### ISSUE TITLE
[ReOpen] YaBAC v0.2.2 : HomeingMovements's Speed Parameter does not accept decimal values

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBACOrganizer#13]
using XV2 XML Serializer v2.5 on 1111_TE1_ALC.bac (Android 21's Appetizing Rush)
the tool reads and saves the floating point number correctly 
![image](https://user-images.githubusercontent.com/47185022/82929151-e2a5ab00-9f8b-11ea-87d4-38cf06a58b61.png)

the same BAC also has an integer value as Speed, which also is read and saved correctly 
![image](https://user-images.githubusercontent.com/47185022/82929205-f4874e00-9f8b-11ea-8570-00d2843b836f.png)

**Comment by KyonkoYuuki** [comment]
You'll need to update the documentation.  Thanks to Lazybones, we now know how this is loaded as a float.
![image](https://user-images.githubusercontent.com/51934173/82952612-4d98b700-9f77-11ea-9a5f-7a8810b27911.png)

It will treat the speed modifier as a float when the horizontal homing arc direction is equal to 7

**Comment by KyonkoYuuki** [comment]
Done
