### ISSUE TITLE
Update YaBAC unknown flags

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBACOrganizer#14]
the Skill / Moveset manual has been recently updated with new information.

most notable ones: 
complete list of Bone Names for Camera, ThrowHandler, Projectile, and Effect entries.
complete list of EyeMovement Direction type flag names
expanded list of ON_OFF_SWITCH flags for Effect

**Comment by KyonkoYuuki** [comment]
Updated the notable ones
