### ISSUE TITLE
YaBAC v0.3.1 : error when pasting entries

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBACOrganizer#15]
in **GOK_PLAYER.BAC**, copy BAC entry 300 and paste over 301
this error message appears 
![image](https://user-images.githubusercontent.com/47185022/83462074-f4e38580-a472-11ea-8f86-282ab138e4f0.png)

**Comment by KyonkoYuuki** [comment]
More misses when refactoring.  God I wish I had tests, but they take too long to write.
