### ISSUE TITLE
YaBAC v0.3.3 : error when pasting entries

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBACOrganizer#16]
in GOK_PLAYER.BAC, copy BAC entry 300 and paste over 301
this error message appears
![image](https://user-images.githubusercontent.com/47185022/83705989-079abd80-a61f-11ea-8a2a-9aeca9a0fd13.png)

**Comment by KyonkoYuuki** [comment]
fixed
