### ISSUE TITLE
New BACType "BACType27" and Homing Movement not saving properly

### ISSUE THREAD

**Issue by pemdasu** [KyonkoYuuki/YaBACOrganizer#17]
In the recent 1.15.0 game update a new BAC entry was added "BACType27". It's still unknown what it does but there is a BAC file in the attachment 
![image](https://user-images.githubusercontent.com/51948142/91621230-ac186b80-e992-11ea-9820-326939845ec7.png)
In the image above is the 1st instance of that BACType in the BAC.

As for the homing movement not saving properly here is what Unleashed said in The Citadel:

"New versions of YaBAC have a bug where it would set all HomingMovement values to 0 after saving
HomingMovement is used for the dashes and stuff
To Fix:
load broken moveset in the YaMov (use an old version, like 0.2.4), then load any other moveset (preferably choose the character that is closest to your modded character)
copy and paste BAC entries 440-446 and save the moveset"

And according to Unleashed it seems happen randomly.

[1121_EL0_GCC.zip](https://github.com/KyonkoYuuki/YaBACOrganizer/files/5144423/1121_EL0_GCC.zip)

**Comment by KyonkoYuuki** [comment]
Added BACType27 and fixed the homing problem for both this and YaMoveset.
