### ISSUE TITLE
0.3.7 : Exception when copying an entry

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBACOrganizer#18]
Traceback (most recent call last):
  File "yabac\panels\main.py", line 483, in on_copy
_pickle.PicklingError: Can't pickle <class 'pyxenoverse.bac.types.physics.Physics'>: it's not the same object as pyxenoverse.bac.types.physics.Physics

to reproduce : copy any entry from any BAC file

**Comment by KyonkoYuuki** [comment]
Fixed, just typoed a name.
