### ISSUE TITLE
critical bug in YaBAC, camera entry

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBACOrganizer#2]
there is a critical bug in YaBAC, camera entry
where the X and Y rotation values are swapped, as, the X value goes in Y, and the Y value goes in X (reads and saves it that way)

**Comment by KyonkoYuuki** [comment]
This stems from the research done on Eternity's genser, which orders it the same way.  I never checked to see if it was correct or not, but it should be brought up with him as well.

**Comment by KyonkoYuuki** [comment]
Flipped x and y, fixed in 0.2.1
