### ISSUE TITLE
BAC tool issue 

### ISSUE THREAD

**Issue by Evt1412** [KyonkoYuuki/YaBACOrganizer#21]
well, i have always problem with the BAC tool verion 2.0 which edit by Unleashed. I noticed Everytime i use that tool it tooks really long if you e.g copy some entries or add subentries by using right click etc.. I hope this bug can be fixed to let the tool run smoothly. 

Thanks.

**Comment by UnleashedGH** [comment]
Don't use my 2.0 edits, those are quite old by now and all their additions were merged in the main repo

**Comment by Evt1412** [comment]
Thank you for waiting a year to get an answer but the problem was solved long ago

**Comment by UnleashedGH** [comment]
Oops, completely missed the date..
although i'm glad the issue is no longer present, so this should be closed now
