### ISSUE TITLE
0.1.8 reads and saves Skill Type incorrectly on BACProjectile

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBACOrganizer#4]
the skill type in the projectile entry always shows as "CMN"

**Comment by KyonkoYuuki** [comment]
I don't see a problem with it.  I do notice from the few skills I picked that they all use CMN more often then not, but I saved and reopened and it loaded correctly in 0.2.0.

**Comment by pemdasu** [comment]
Why did this happen lmao
