### ISSUE TITLE
Delete "HasDummy" entries when saving BAC

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBACOrganizer#5]
in a BAC file, the HasDummy entries can disable a BacType ID
for example, HasDummy11 will disable BacType11 (Sound)
and so the sound entry won't work at all. and because YaBAC doesn't show the HasDummy entries (unlike in xml) it can be quite confusing when the Sound entry is setup correctly, but doesn't work.

so maybe if YaBAC can just auto-delete those entries when saving BAC

**Comment by KyonkoYuuki** [comment]
You'll have to explain that more, I'm unfamiliar with HasDummy entries.

**Comment by UnleashedGH** [comment]
> You'll have to explain that more, I'm unfamiliar with HasDummy entries.

they are subentries that appear when serializing a BAC file either with Genser or lazybone XML serializer, they are basically "null" entries that have an ID, and they are labeled as "HasDummy" in lazybone xml serializer and "HAS_DUMMY" in Genser

**Comment by KyonkoYuuki** [comment]
Updated pyxenoverse to remove dummy entries when saving.
