### ISSUE TITLE
v0.2.0 still reads and saves Skill Type incorrectly on BACProjectile

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBACOrganizer#7]
for example, Super Kamehameha should have its Projectile Skill Type as 0x6 (Ultimate)
but it reads as CMN. 

although it does save as 0x6

**Comment by KyonkoYuuki** [comment]
So genser is wrong then?  This is from Super Kamehameha.

        <Projectile>
            <START_TIME value="92" />
            <DURATION value="1" />
            <U_04 value="0x0" />
            <FLAGS value="0x0" />
            <SKILL_ID value="0" />
            
            <CAN_USE_CMN_BSA value="0x0" />
            <PROJECTILE_ID value="0" />
            <BONE_TO_SPAWN_FROM value="0x14" />
            <SPAWN_SOURCE value="0x300" />
            <POSITION value="0.0, 0.0, 0.0" />
            <SKILL_TYPE value="0x0" />
            <U_24 value="0x0" />
            <F_28 value="0.0" />
            <U_2C value="0x6" />
            <U_2E value="0x0" />
            <PROJECTILE_HEALTH value="0" />
            <U_34 value="0x0, 0x0, 0x0" />
        </Projectile>

**Comment by KyonkoYuuki** [comment]
note the U_2C value

**Comment by KyonkoYuuki** [comment]
Well some more checking and its wrong in genser.  Lazybone's has it right.  Fixed in 0.2.1
