### ISSUE TITLE
YaBAC not setting SIZE_SMALL correctly (ThrowHandler)

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBACOrganizer#8]
BAC files have a SIZE_SMALL tag (boolean) meant for BacType17, it's used in older BAC files to 
compensate for the missing VICTIM_DISPLACEMENT property found in new BAC files

YaBAC does read ThrowHandler correctly, but it seems it always sets SIZE_SMALL to "True" regardless if it was true or not, and also removes any VICTIM_DISPLACEMENT properties found in the BAC file

**Comment by KyonkoYuuki** [comment]
Fixed now.  It can now detect the throws correctly.
